version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis_container
    ports:
      - '6379:6379'
    volumes:
      - data:/redis_data

  server:
    build:
      context: .
      dockerfile: Dockerfile
    image: nodejs
    container_name: nodejs
    restart: unless-stopped
    env_file: .env
    # environment:
    ports:
      - "5000:5000"
    networks:
      - app-network
    # command: ./wait-for.sh db:27017 -- /home/node/app/node_modules/.bin/nodemon app.js

volumes:
  data:
